;;; customs-defaults.el --- Committed baseline custom-set-variables -*- lexical-binding: t -*-

;; This file holds intentional defaults that are safe to commit.
;; Machine-specific or automatically-generated overrides belong in
;; customs.el (gitignored).
;;
;; Do NOT edit this file through M-x customize; those writes go to
;; customs.el.  Edit this file directly instead.

(custom-set-variables
 ;; Keep more recently visited files in the recentf list.
 '(recentf-max-saved-items 70)
 ;; Allow the pp-buffer + indent-buffer combo as a safe dir-local eval
 ;; (useful for pretty-printing Elisp files on open).
 '(safe-local-variable-values '((eval progn (pp-buffer) (indent-buffer))))
 ;; Default to 4-space tab display width.
 '(tab-width 4))

(custom-set-faces)
